# Site settings
title: Kamel Ouzouigh Blog
description: "Kamel Ouzouigh Programming Blog"
url: "https://kouzouigh.github.io/blog"
logo: "https://kouzouigh.github.io/blog/img/coffee.svg"
author:
  name: "Kamel Ouzouigh"
  email: "ouzouighkamel@gmail.com"
  url: "https://kouzouigh.github.io"

twitter: 
  username: onyme001

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Google Analytics
google_analytics: UA-17222824-2

webmaster_verifications:
  google: 987654321
  bing: 987654321
  alexa: 987654321

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag